### ISSUE TITLE
Reducing the folder size

### ISSUE THREAD

**Issue by Dersh** [Banuba/face-ar-flutter-sample#10]
Are there any ways to reduce the size of this folder?
Is it possible to make an example so that the libraries are downloaded over the network during the first run?
![photo_2022-12-08_10-35-39](https://user-images.githubusercontent.com/28646/208080541-0dabcaee-97e4-415e-92e1-22ef1fbf16d4.jpg)

**Comment by sdk-banuba** [comment]
The problem discussed here is similar to [this](https://github.com/Banuba/face-ar-flutter-sample/issues/8) ticket.

On demand resources loading is also [possible](https://docs.banuba.com/face-ar-sdk-v1/android/tutorials/android_external_resources/) but it quite tricky and not recommended.
