### ISSUE TITLE
Excluding blush-texts

### ISSUE THREAD

**Issue by Dersh** [Banuba/face-ar-flutter-sample#8]
Hello

Is there any opportunity to exclude blush-texts? We don't use this package and it adds to much to the application size.

![photo_2022-12-08_09-21-56](https://user-images.githubusercontent.com/28646/208078219-eb98fa82-1230-4c43-a6a4-044f49e7718d.jpg)

**Comment by sdk-banuba** [comment]
@Dersh,
This example depends on `banuba_sdk` metapackage, which simply depends on all Banuba SDK packages. In your real app you should decide what packages to pick for release. Please, refer [this](https://docs.banuba.com/face-ar-sdk-v1/core/tutorials/using_packages).

**Comment by sdk-banuba** [comment]
FYI, dependencies are listed [here](https://github.com/Banuba/face-ar-flutter-sample/blob/master/android/app/build.gradle#L73)

**Comment by Dersh** [comment]
It doesn't help at all.
[this](https://docs.banuba.com/face-ar-sdk-v1/core/tutorials/using_packages) change causes me to replace:
```
implementation "com.banuba.sdk:banuba_sdk:1.5.1"
```
with this one:
```
    //implementation "com.banuba.sdk:banuba_sdk:1.5.1"
    //implementation "com.banuba.sdk:sdk_core:1.5.1"
    //implementation "com.banuba.sdk:effect_player:1.5.1"
    //implementation "com.banuba.sdk:scripting:1.5.1"
    implementation "com.banuba.sdk:face_tracker:1.5.1"
    implementation "com.banuba.sdk:lips:1.5.1"
    implementation "com.banuba.sdk:hair:1.5.1"
    //implementation "com.banuba.sdk:hands:1.5.1"
    //implementation "com.banuba.sdk:occlusion:1.5.1"
    implementation "com.banuba.sdk:eyes:1.5.1"
    implementation "com.banuba.sdk:skin:1.5.1"
    //implementation "com.banuba.sdk:background:1.5.1"
    //implementation "com.banuba.sdk:body:1.5.1"
    implementation "com.banuba.sdk:acne_eyebags_removal:1.5.1"
    implementation "com.banuba.sdk:correctors:1.5.1"
    implementation "com.banuba.sdk:brows:1.5.1"
    implementation "com.banuba.sdk:neurobeauty_makeup:1.5.1"
    implementation "com.banuba.sdk:banuba_sdk_resources:1.5.1"
```
The resulting size of the package is increased
Before:
app-release.apk (278.8MB).

After:
app-release.apk (279.8MB).

Should I do it in another manner?
What should I do to remove 'blush' itself?

**Comment by sdk-banuba** [comment]
I believe you don't need com.banuba.sdk:neurobeauty_makeup -- it is rather rare package to use. Also, banuba_sdk_resources in most cases is redundant. Please, remove it too. 

For your note, generally we track our support here https://docs.banuba.com/face-ar-sdk-v1/support .
Tickets in github usually just closed after reply.
