### ISSUE TITLE
Excluding of unnecessary packages

### ISSUE THREAD

**Issue by Dersh** [Banuba/face-ar-flutter-sample#9]
Could you please exclude marked packages as we don't use them and try to decrease the app size:
![photo_2022-12-08_09-20-31](https://user-images.githubusercontent.com/28646/208078992-3c8d582e-9c74-4746-af44-7cdb373bd465.jpg)

**Comment by sdk-banuba** [comment]
Duplicates [this](https://github.com/Banuba/face-ar-flutter-sample/issues/8)
